In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
import os



In [5]:
os.getcwd()

'C:\\Users\\Rishi'

In [7]:
os.chdir('C:\\Users\\Rishi\\OneDrive\\Desktop\\Data Sci\\Acmegrade Data Science July_23 Files\\Jul 23 DS Day 16\\Projects\\Detection of Parkinsons Disease\\')

In [8]:
os.getcwd()

'C:\\Users\\Rishi\\OneDrive\\Desktop\\Data Sci\\Acmegrade Data Science July_23 Files\\Jul 23 DS Day 16\\Projects\\Detection of Parkinsons Disease'

In [11]:
df=pd.read_csv('parkinsons.data')
display(df)

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0    phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1    phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2    phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3    phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4    phon_R01_S01_5      116.014       141.781       110.655         0.01284   
..              ...          ...           ...           ...             ...   
190  phon_R01_S50_2      174.188       230.978        94.261         0.00459   
191  phon_R01_S50_3      209.516       253.017        89.488         0.00564   
192  phon_R01_S50_4      174.688       240.005        74.287         0.01360   
193  phon_R01_S50_5      198.764       396.961        74.904         0.00740   
194  phon_R01_S50_6      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0             0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1             0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2             0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3             0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4             0.00011   0.00655   0.00908     0.01966       0.06425  ...   
..                ...       ...       ...         ...           ...  ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087  ...   
191           0.00003   0.00331   0.00292     0.00994       0.02751  ...   
192           0.00008   0.00624   0.00564     0.01873       0.02308  ...   
193           0.00004   0.00370   0.00390     0.01109       0.02296  ...   
194           0.00003   0.00295   0.00317     0.00885       0.01884  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0        0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1        0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2        0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3        0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4        0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   
..           ...      ...     ...     ...       ...       ...       ...   
190      0.07008  0.02764  19.517       0  0.448439  0.657899 -6.538586   
191      0.04812  0.01810  19.147       0  0.431674  0.683244 -6.195325   
192      0.03804  0.10715  17.883       0  0.407567  0.655683 -6.787197   
193      0.03794  0.07223  19.020       0  0.451221  0.643956 -6.744577   
194      0.03078  0.04398  21.209       0  0.462803  0.664357 -5.724056   

      spread2        D2       PPE  
0    0.266482  2.301442  0.284654  
1    0.335590  2.486855  0.368674  
2    0.311173  2.342259  0.332634  
3    0.334147  2.405554  0.368975  
4    0.234513  2.332180  0.410335  
..        ...       ...       ...  
190  0.121952  2.657476  0.133050  
191  0.129303  2.784312  0.168895  
192  0.158453  2.679772  0.131728  
193  0.207454  2.138608  0.123306  
194  0.190667  2.555477  0.148569  

[195 rows x 24 columns]

In [12]:
print(len(df))

195


In [13]:
display(df.shape)

(195, 24)

In [14]:
display(df.dtypes)

name                 object
MDVP:Fo(Hz)         float64
MDVP:Fhi(Hz)        float64
MDVP:Flo(Hz)        float64
MDVP:Jitter(%)      float64
MDVP:Jitter(Abs)    float64
MDVP:RAP            float64
MDVP:PPQ            float64
Jitter:DDP          float64
MDVP:Shimmer        float64
MDVP:Shimmer(dB)    float64
Shimmer:APQ3        float64
Shimmer:APQ5        float64
MDVP:APQ            float64
Shimmer:DDA         float64
NHR                 float64
HNR                 float64
status                int64
RPDE                float64
DFA                 float64
spread1             float64
spread2             float64
D2                  float64
PPE                 float64
dtype: object

In [15]:
display (df.isna().sum())

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [16]:
df.drop(['name'],axis=1,inplace=True)
display (df)


MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0        119.992       157.302        74.997         0.00784   
1        122.400       148.650       113.819         0.00968   
2        116.682       131.111       111.555         0.01050   
3        116.676       137.871       111.366         0.00997   
4        116.014       141.781       110.655         0.01284   
..           ...           ...           ...             ...   
190      174.188       230.978        94.261         0.00459   
191      209.516       253.017        89.488         0.00564   
192      174.688       240.005        74.287         0.01360   
193      198.764       396.961        74.904         0.00740   
194      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0             0.00007   0.00370   0.00554     0.01109       0.04374   
1             0.00008   0.00465   0.00696     0.01394       0.06134   
2             0.00009   0.00544   0.00781     0.01633       0.05233   
3             0.00009   0.00502   0.00698     0.01505       0.05492   
4             0.00011   0.00655   0.00908     0.01966       0.06425   
..                ...       ...       ...         ...           ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087   
191           0.00003   0.00331   0.00292     0.00994       0.02751   
192           0.00008   0.00624   0.00564     0.01873       0.02308   
193           0.00004   0.00370   0.00390     0.01109       0.02296   
194           0.00003   0.00295   0.00317     0.00885       0.01884   

     MDVP:Shimmer(dB)  ...  Shimmer:DDA      NHR     HNR  status      RPDE  \
0               0.426  ...      0.06545  0.02211  21.033       1  0.414783   
1               0.626  ...      0.09403  0.01929  19.085       1  0.458359   
2               0.482  ...      0.08270  0.01309  20.651       1  0.429895   
3               0.517  ...      0.08771  0.01353  20.644       1  0.434969   
4               0.584  ...      0.10470  0.01767  19.649       1  0.417356   
..                ...  ...          ...      ...     ...     ...       ...   
190             0.405  ...      0.07008  0.02764  19.517       0  0.448439   
191             0.263  ...      0.04812  0.01810  19.147       0  0.431674   
192             0.256  ...      0.03804  0.10715  17.883       0  0.407567   
193             0.241  ...      0.03794  0.07223  19.020       0  0.451221   
194             0.190  ...      0.03078  0.04398  21.209       0  0.462803   

          DFA   spread1   spread2        D2       PPE  
0    0.815285 -4.813031  0.266482  2.301442  0.284654  
1    0.819521 -4.075192  0.335590  2.486855  0.368674  
2    0.825288 -4.443179  0.311173  2.342259  0.332634  
3    0.819235 -4.117501  0.334147  2.405554  0.368975  
4    0.823484 -3.747787  0.234513  2.332180  0.410335  
..        ...       ...       ...       ...       ...  
190  0.657899 -6.538586  0.121952  2.657476  0.133050  
191  0.683244 -6.195325  0.129303  2.784312  0.168895  
192  0.655683 -6.787197  0.158453  2.679772  0.131728  
193  0.643956 -6.744577  0.207454  2.138608  0.123306  
194  0.664357 -5.724056  0.190667  2.555477  0.148569  

[195 rows x 23 columns]

In [17]:
X=df.drop(labels=['status'],axis=1)
Y=df['status']
display(X,Y)

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0        119.992       157.302        74.997         0.00784   
1        122.400       148.650       113.819         0.00968   
2        116.682       131.111       111.555         0.01050   
3        116.676       137.871       111.366         0.00997   
4        116.014       141.781       110.655         0.01284   
..           ...           ...           ...             ...   
190      174.188       230.978        94.261         0.00459   
191      209.516       253.017        89.488         0.00564   
192      174.688       240.005        74.287         0.01360   
193      198.764       396.961        74.904         0.00740   
194      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0             0.00007   0.00370   0.00554     0.01109       0.04374   
1             0.00008   0.00465   0.00696     0.01394       0.06134   
2             0.00009   0.00544   0.00781     0.01633       0.05233   
3             0.00009   0.00502   0.00698     0.01505       0.05492   
4             0.00011   0.00655   0.00908     0.01966       0.06425   
..                ...       ...       ...         ...           ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087   
191           0.00003   0.00331   0.00292     0.00994       0.02751   
192           0.00008   0.00624   0.00564     0.01873       0.02308   
193           0.00004   0.00370   0.00390     0.01109       0.02296   
194           0.00003   0.00295   0.00317     0.00885       0.01884   

     MDVP:Shimmer(dB)  ...  MDVP:APQ  Shimmer:DDA      NHR     HNR      RPDE  \
0               0.426  ...   0.02971      0.06545  0.02211  21.033  0.414783   
1               0.626  ...   0.04368      0.09403  0.01929  19.085  0.458359   
2               0.482  ...   0.03590      0.08270  0.01309  20.651  0.429895   
3               0.517  ...   0.03772      0.08771  0.01353  20.644  0.434969   
4               0.584  ...   0.04465      0.10470  0.01767  19.649  0.417356   
..                ...  ...       ...          ...      ...     ...       ...   
190             0.405  ...   0.02745      0.07008  0.02764  19.517  0.448439   
191             0.263  ...   0.01879      0.04812  0.01810  19.147  0.431674   
192             0.256  ...   0.01667      0.03804  0.10715  17.883  0.407567   
193             0.241  ...   0.01588      0.03794  0.07223  19.020  0.451221   
194             0.190  ...   0.01373      0.03078  0.04398  21.209  0.462803   

          DFA   spread1   spread2        D2       PPE  
0    0.815285 -4.813031  0.266482  2.301442  0.284654  
1    0.819521 -4.075192  0.335590  2.486855  0.368674  
2    0.825288 -4.443179  0.311173  2.342259  0.332634  
3    0.819235 -4.117501  0.334147  2.405554  0.368975  
4    0.823484 -3.747787  0.234513  2.332180  0.410335  
..        ...       ...       ...       ...       ...  
190  0.657899 -6.538586  0.121952  2.657476  0.133050  
191  0.683244 -6.195325  0.129303  2.784312  0.168895  
192  0.655683 -6.787197  0.158453  2.679772  0.131728  
193  0.643956 -6.744577  0.207454  2.138608  0.123306  
194  0.664357 -5.724056  0.190667  2.555477  0.148569  

[195 rows x 22 columns]

0      1
1      1
2      1
3      1
4      1
      ..
190    0
191    0
192    0
193    0
194    0
Name: status, Length: 195, dtype: int64

In [18]:
X_tr,X_te,Y_tr,Y_te=train_test_split(X,Y,test_size=0.25,random_state=49)
print (X.shape,Y.shape)
print(X_tr.shape,X_te.shape,Y_tr.shape,Y_te.shape)



(195, 22) (195,)
(146, 22) (49, 22) (146,) (49,)


In [19]:
corr = df.corr()
display (corr)

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
MDVP:Fo(Hz)          1.000000      0.400985      0.596546       -0.118003   
MDVP:Fhi(Hz)         0.400985      1.000000      0.084951        0.102086   
MDVP:Flo(Hz)         0.596546      0.084951      1.000000       -0.139919   
MDVP:Jitter(%)      -0.118003      0.102086     -0.139919        1.000000   
MDVP:Jitter(Abs)    -0.382027     -0.029198     -0.277815        0.935714   
MDVP:RAP            -0.076194      0.097177     -0.100519        0.990276   
MDVP:PPQ            -0.112165      0.091126     -0.095828        0.974256   
Jitter:DDP          -0.076213      0.097150     -0.100488        0.990276   
MDVP:Shimmer        -0.098374      0.002281     -0.144543        0.769063   
MDVP:Shimmer(dB)    -0.073742      0.043465     -0.119089        0.804289   
Shimmer:APQ3        -0.094717     -0.003743     -0.150747        0.746625   
Shimmer:APQ5        -0.070682     -0.009997     -0.101095        0.725561   
MDVP:APQ            -0.077774      0.004937     -0.107293        0.758255   
Shimmer:DDA         -0.094732     -0.003733     -0.150737        0.746635   
NHR                 -0.021981      0.163766     -0.108670        0.906959   
HNR                  0.059144     -0.024893      0.210851       -0.728165   
status              -0.383535     -0.166136     -0.380200        0.278220   
RPDE                -0.383894     -0.112404     -0.400143        0.360673   
DFA                 -0.446013     -0.343097     -0.050406        0.098572   
spread1             -0.413738     -0.076658     -0.394857        0.693577   
spread2             -0.249450     -0.002954     -0.243829        0.385123   
D2                   0.177980      0.176323     -0.100629        0.433434   
PPE                 -0.372356     -0.069543     -0.340071        0.721543   

                  MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  \
MDVP:Fo(Hz)              -0.382027 -0.076194 -0.112165   -0.076213   
MDVP:Fhi(Hz)             -0.029198  0.097177  0.091126    0.097150   
MDVP:Flo(Hz)             -0.277815 -0.100519 -0.095828   -0.100488   
MDVP:Jitter(%)            0.935714  0.990276  0.974256    0.990276   
MDVP:Jitter(Abs)          1.000000  0.922911  0.897778    0.922913   
MDVP:RAP                  0.922911  1.000000  0.957317    1.000000   
MDVP:PPQ                  0.897778  0.957317  1.000000    0.957319   
Jitter:DDP                0.922913  1.000000  0.957319    1.000000   
MDVP:Shimmer              0.703322  0.759581  0.797826    0.759555   
MDVP:Shimmer(dB)          0.716601  0.790652  0.839239    0.790621   
Shimmer:APQ3              0.697153  0.744912  0.763580    0.744894   
Shimmer:APQ5              0.648961  0.709927  0.786780    0.709907   
MDVP:APQ                  0.648793  0.737455  0.804139    0.737439   
Shimmer:DDA               0.697170  0.744919  0.763592    0.744901   
NHR                       0.834972  0.919521  0.844604    0.919548   
HNR                      -0.656810 -0.721543 -0.731510   -0.721494   
status                    0.338653  0.266668  0.288698    0.266646   
RPDE                      0.441839  0.342140  0.333274    0.342079   
DFA                       0.175036  0.064083  0.196301    0.064026   
spread1                   0.735779  0.648328  0.716489    0.648328   
spread2                   0.388543  0.324407  0.407605    0.324377   
D2                        0.310694  0.426605  0.412524    0.426556   
PPE                       0.748162  0.670999  0.769647    0.671005   

                  MDVP:Shimmer  MDVP:Shimmer(dB)  ...  Shimmer:DDA       NHR  \
MDVP:Fo(Hz)          -0.098374         -0.073742  ...    -0.094732 -0.021981   
MDVP:Fhi(Hz)          0.002281          0.043465  ...    -0.003733  0.163766   
MDVP:Flo(Hz)         -0.144543         -0.119089  ...    -0.150737 -0.108670   
MDVP:Jitter(%)        0.769063          0.804289  ...     0.746635  0.906959   
MDVP:Jitter(Abs)      0.703322          0.716601  ...     0.697170  0.834972   
MDVP:RAP

In [21]:
log_r = LogisticRegression().fit(X_tr, Y_tr)
train_pre = log_r.predict(X_tr)
print("acc on train : ", accuracy_score(Y_tr, train_pre))
test_pre = log_r.predict(X_te)
print("acc on test : ", accuracy_score(Y_te, test_pre))



acc on train :  0.8698630136986302
acc on test :  0.8571428571428571


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
print(confusion_matrix(Y_tr, train_pre))
print("confusion_matrix test is:\n ",confusion_matrix(Y_te, test_pre))
print('\nClassification Report Train')
print(classification_report (Y_tr, train_pre))
print('\nClassification Report Test')
print(classification_report (Y_te, test_pre))


[[ 23  15]
 [  4 104]]
confusion_matrix test is:
  [[ 6  4]
 [ 3 36]]

Classification Report Train
              precision    recall  f1-score   support

           0       0.85      0.61      0.71        38
           1       0.87      0.96      0.92       108

    accuracy                           0.87       146
   macro avg       0.86      0.78      0.81       146
weighted avg       0.87      0.87      0.86       146


Classification Report Test
              precision    recall  f1-score   support

           0       0.67      0.60      0.63        10
           1       0.90      0.92      0.91        39

    accuracy                           0.86        49
   macro avg       0.78      0.76      0.77        49
weighted avg       0.85      0.86      0.85        49



In [23]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier().fit(X,Y)
train_pre1=dt.predict(X_tr)
print("train acc:", accuracy_score(Y_tr,train_pre1))

train acc: 1.0


In [24]:
test_pre1=dt.predict(X_te)
print("test acc:", accuracy_score(Y_te,test_pre1))

test acc: 1.0


In [28]:
print(metrics.cohen_kappa_score(Y_te,test_pre1))

1.0


In [30]:
print("confusion mat train\n", confusion_matrix(Y_tr,train_pre1))

confusion mat train
 [[ 38   0]
 [  0 108]]


In [32]:
print("confusion mat test\n", confusion_matrix(Y_te,test_pre1))

confusion mat test
 [[10  0]
 [ 0 39]]


In [79]:
RF=RandomForestClassifier().fit(X_tr,Y_tr)
train_pre2 = RF.predict(X_tr)
print("TRAIN ACC:", accuracy_score(Y_tr,train_pre2))

TRAIN ACC: 1.0


In [82]:
test_pre2=RF.predict(X_te)
print("test acc:",accuracy_score(Y_te,test_pre2))

test acc: 0.8979591836734694


In [85]:
print("confusion mat train\n", confusion_matrix(Y_tr,train_pre2))

confusion mat train
 [[ 38   0]
 [  0 108]]


In [86]:
print("confusion mat test\n", confusion_matrix(Y_te,test_pre2))

confusion mat test
 [[ 6  4]
 [ 1 38]]


In [91]:
print(metrics.cohen_kappa_score(Y_te,test_pre2))

0.6464646464646464


In [34]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_tr,Y_tr)
train_pre3=nb.predict(X_tr)
test_pre3=nb.predict(X_te)

In [36]:
print("train accuracy= ", accuracy_score(Y_tr,train_pre3))
print("test accuracy= ", accuracy_score(Y_te,test_pre3))


train accuracy=  0.7328767123287672
test accuracy=  0.6938775510204082


In [38]:
print("confusion train \n", confusion_matrix(Y_tr,train_pre3))
print("confusion test \n", confusion_matrix(Y_te,test_pre3))

confusion train 
 [[36  2]
 [37 71]]
confusion test 
 [[ 9  1]
 [14 25]]


In [39]:
print('KappaScore is: ', metrics.cohen_kappa_score(Y_te,test_pre3))

KappaScore is:  0.3647363872082974


In [41]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_tr,Y_tr)
train_pre4=knn.predict(X_tr)
test_pre4=knn.predict(X_te)

In [42]:
print( "train acc= ", accuracy_score(Y_tr,train_pre4))
print( "test acc= ", accuracy_score(Y_te,test_pre4))


train acc=  0.8767123287671232
test acc=  0.8979591836734694


In [43]:
print("kappa score= ",metrics.cohen_kappa_score(Y_te,test_pre4))

kappa score=  0.6464646464646464


In [46]:
print("confusion test matrix\n", confusion_matrix(Y_te,test_pre4))

confusion test matrix
 [[ 6  4]
 [ 1 38]]


In [47]:
print("confusion train matrix\n", confusion_matrix(Y_tr,train_pre4))

confusion train matrix
 [[ 24  14]
 [  4 104]]


In [49]:
from sklearn.svm import SVC
svm=SVC(kernel='linear')
svm.fit(X_tr,Y_tr)

SVC(kernel='linear')

In [50]:
train_pre5=svm.predict(X_tr)
print("train acc= ", accuracy_score(Y_tr,train_pre5))
test_pre5=svm.predict(X_te)
print("test acc= ", accuracy_score(Y_te,test_pre5))

train acc=  0.8698630136986302
test acc=  0.8367346938775511


In [51]:
print("train confusion \n", confusion_matrix(Y_tr,train_pre5))
print("test confusion \n", confusion_matrix(Y_te,test_pre5))

train confusion 
 [[ 22  16]
 [  3 105]]
test confusion 
 [[ 5  5]
 [ 3 36]]


In [52]:
print("kappa score= ", metrics.cohen_kappa_score(Y_te,test_pre5))

kappa score=  0.4570637119113573


In [54]:
import pickle 
pickle.dump(svm,open('deploy_SVM.pkl','wb'))
model=pickle.load(open('deploy_SVM.pkl','rb'))

In [58]:
train_pre6=model.predict (X_tr)
print("train acc= ", accuracy_score(Y_tr,train_pre6))

train acc=  0.8698630136986302


In [59]:
test_pre6=model.predict(X_te)
print("test acc= ", accuracy_score(Y_te,test_pre6))

test acc=  0.8367346938775511


In [60]:
print('KappaScore is: ', metrics.cohen_kappa_score(Y_te,test_pre6))

KappaScore is:  0.4570637119113573
